import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  BrainCircuit, 
  Sparkles, 
  Zap, 
  Lightbulb, 
  AlertTriangle, 
  ArrowRight,
  Loader2,
  RefreshCcw
} from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { cn } from '../../lib/utils';

export const AIInsightsCenter = () => {
  const [isGenerating, setIsGenerating] = useState(false);
  const [insight, setInsight] = useState<string | null>(null);

  const generateInsights = async () => {
    setIsGenerating(true);
    try {
      const response = await fetch('/api/gemini/insights', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ 
          data: {
            stores: 4200,
            revenue: 1250000,
            growth: 14.2,
            topCategories: ['Burgers', 'Sides', 'Drinks'],
            regionalWeakness: 'Southeast Asia',
            peakHours: '12:00-14:00, 18:00-20:00'
          }
        }),
      });
      const data = await response.json();
      setInsight(data.text);
    } catch (error) {
      console.error(error);
      setInsight("ERR: System connection failed. Please verify API protocols.");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="space-y-8 max-w-5xl mx-auto">
      <div className="text-center space-y-4">
        <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full glass border-[#F27D26]/20 text-[#F27D26] text-xs font-bold uppercase tracking-widest">
          <BrainCircuit className="w-4 h-4" />
          Flame Intelligence v4.2
        </div>
        <h1 className="text-5xl font-display font-bold text-white tracking-tight">AI Strategy Center</h1>
        <p className="text-white/40 text-lg max-w-2xl mx-auto">
          Predictive analytics and strategic directives generated by the core FlameOS engine.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        <div className="glass rounded-3xl p-8 relative overflow-hidden flex flex-col justify-between group">
          <div className="absolute -top-24 -right-24 w-64 h-64 bg-[#F27D26]/10 rounded-full blur-3xl group-hover:bg-[#F27D26]/20 transition-colors" />
          
          <div>
            <div className="p-3 w-12 h-12 rounded-2xl bg-[#F27D26]/10 text-[#F27D26] mb-6">
              <Sparkles className="w-6 h-6" />
            </div>
            <h3 className="text-2xl font-display font-bold text-white mb-4">Strategic Forecasting</h3>
            <p className="text-white/40 mb-8 leading-relaxed">
              Analyze current market trends, inventory velocity, and labor efficiency to generate next-quarter directives.
            </p>
          </div>
          
          <button 
            onClick={generateInsights}
            disabled={isGenerating}
            className="w-full py-4 rounded-2xl flame-gradient text-white font-bold flex items-center justify-center gap-3 transition-all hover:scale-[1.02] active:scale-[0.98] disabled:opacity-50 disabled:scale-100"
          >
            {isGenerating ? (
              <Loader2 className="w-5 h-5 animate-spin" />
            ) : (
              <Zap className="w-5 h-5" />
            )}
            {isGenerating ? 'Synthesizing...' : 'Generate Executive Directives'}
          </button>
        </div>

        <div className="glass rounded-3xl p-8 border-[#F27D26]/20">
          <div className="flex items-center justify-between mb-8">
            <h3 className="text-xl font-display font-bold text-white">Live Anomalies</h3>
            <span className="flex items-center gap-1 text-[10px] text-[#FFB30F] font-bold uppercase tracking-widest ring-1 ring-[#FFB30F]/20 px-2 py-0.5 rounded-full">
              Monitoring
            </span>
          </div>
          
          <div className="space-y-4">
            {[
              { icon: AlertTriangle, color: 'text-[#D62300]', bg: 'bg-[#D62300]/10', label: 'Revenue Leakage', desc: 'Predicting 12% drop in Miami sector due to supply chain hitch.' },
              { icon: Lightbulb, color: 'text-[#FFB30F]', bg: 'bg-[#FFB30F]/10', label: 'Product Optimization', desc: 'New "Angry Whopper" variation showing 94th percentile viral potential.' },
            ].map((item, i) => (
              <div key={i} className="p-4 rounded-2xl bg-white/5 border border-white/5 hover:border-white/10 transition-all flex gap-4">
                 <div className={cn("p-2 rounded-xl h-fit", item.bg, item.color)}>
                   <item.icon className="w-4 h-4" />
                 </div>
                 <div>
                   <p className="text-sm font-bold text-white mb-1">{item.label}</p>
                   <p className="text-xs text-white/40 leading-relaxed">{item.desc}</p>
                 </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      <AnimatePresence>
        {insight && (
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 20 }}
            className="glass rounded-[2rem] p-10 border-[#F27D26]/30 relative"
          >
            <div className="absolute top-6 right-6">
              <button 
                onClick={() => setInsight(null)}
                className="p-2 hover:bg-white/5 rounded-full text-white/20 hover:text-white"
              >
                <RefreshCcw className="w-4 h-4" />
              </button>
            </div>
            
            <div className="prose prose-invert max-w-none prose-headings:font-display prose-headings:tracking-tight prose-p:text-white/60 prose-p:leading-relaxed prose-strong:text-[#F27D26]">
              <ReactMarkdown>{insight}</ReactMarkdown>
            </div>
            
            <div className="mt-10 flex flex-wrap gap-4">
              <button className="px-6 py-3 rounded-xl bg-[#F27D26] text-white text-sm font-bold flex items-center gap-2 hover:bg-[#D62300] transition-colors">
                Implement Strategy <ArrowRight className="w-4 h-4" />
              </button>
              <button className="px-6 py-3 rounded-xl glass border-white/10 text-white text-sm font-bold">
                Export to Regionals
              </button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};
